#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

// Legge le directory da env (Makefile può passarle)
const GENERATED_DIR = process.env.GENERATED_DIR || path.join('src', '.generated');
const BUILD_DIR = process.env.BUILD_DIR || '_build';

// Legge le variabili di metadata (fornite da Makefile / CLI o fallback)
const vars = {
  FRIENDLY_NAME: process.env.FRIENDLY_NAME || 'Multi Monitor Enhanced',
  NAME: process.env.NAME || 'multi-monitor-enhanced',
  DOMAIN: process.env.DOMAIN || 'berik-99',
  DESCRIPTION: process.env.DESCRIPTION || 'Enhance multi-monitor support in GNOME Shell',
  URL: process.env.URL || 'https://github.com/berik-99/multi-monitor-enhanced',
  SETTINGS_SCHEMA_ID: process.env.SETTINGS_SCHEMA_ID || 'org.gnome.shell.extensions.',
  GETTEXT_DOMAIN: process.env.GETTEXT_DOMAIN || process.env.NAME || 'multi-monitor-enhanced',
  VERSION: process.env.VERSION || '1',
  SHELL_VERSION: process.env.SHELL_VERSION || '45,46,47,48,49',
  UUID: process.env.UUID || undefined, // opzionale, Makefile può passare UUID
};

// Normalizza shell-version in array di stringhe
const shellVersionArray = String(vars.SHELL_VERSION)
  .split(',')
  .map(s => s.trim())
  .filter(s => s.length > 0);

// Costruisci metadata.json
const metadata = {
  name: vars.FRIENDLY_NAME,
  description: vars.DESCRIPTION,
  uuid: vars.UUID ? vars.UUID : `${vars.NAME}@${vars.DOMAIN}`,
  url: vars.URL,
  "settings-schema": `${vars.SETTINGS_SCHEMA_ID}${vars.NAME}`,
  "gettext-domain": vars.GETTEXT_DOMAIN,
  version: Number(vars.VERSION) || vars.VERSION,
  "shell-version": shellVersionArray,
};

// Assicura che le cartelle esistano
const buildDir = path.resolve(process.cwd(), BUILD_DIR);
const genDir = path.resolve(process.cwd(), GENERATED_DIR);

ensureDir(buildDir);
ensureDir(genDir);

// Scrivi metadata.json in BUILD_DIR
const metadataPath = path.join(buildDir, 'metadata.json');
fs.writeFileSync(metadataPath, JSON.stringify(metadata, null, 4), 'utf8');
console.log(`Wrote ${metadataPath}`);

// Scrivi file TypeScript esportato con le variabili (per import)
const tsContent = `// This file is auto-generated by ${path.basename(__filename)}
// Do not edit by hand.

export const FRIENDLY_NAME = ${JSON.stringify(vars.FRIENDLY_NAME)};
export const NAME = ${JSON.stringify(vars.NAME)};
export const DOMAIN = ${JSON.stringify(vars.DOMAIN)};
export const DESCRIPTION = ${JSON.stringify(vars.DESCRIPTION)};
export const URL = ${JSON.stringify(vars.URL)};
export const SETTINGS_SCHEMA_ID = ${JSON.stringify(vars.SETTINGS_SCHEMA_ID)};
export const SETTINGS_SCHEMA = ${JSON.stringify(`${vars.SETTINGS_SCHEMA_ID}${vars.NAME}`)};
export const GETTEXT_DOMAIN = ${JSON.stringify(vars.GETTEXT_DOMAIN)};
export const VERSION = ${Number(vars.VERSION) || JSON.stringify(vars.VERSION)};
export const SHELL_VERSION = ${JSON.stringify(shellVersionArray)};
export const UUID = ${JSON.stringify(metadata.uuid)};
`;
fs.writeFileSync(path.join(genDir, 'env.ts'), tsContent, 'utf8');
console.log(`Wrote ${path.join(genDir, 'env.ts')}`);

// Scrivi file di dichiarazione globali per TypeScript (opzionale)
const dtsContent = `// This file is auto-generated by ${path.basename(__filename)}
// Declares globals so you can access variables without import (optional).
declare global {
  const FRIENDLY_NAME: string;
  const NAME: string;
  const DOMAIN: string;
  const DESCRIPTION: string;
  const URL: string;
  const SETTINGS_SCHEMA_ID: string;
  const SETTINGS_SCHEMA: string;
  const GETTEXT_DOMAIN: string;
  const VERSION: number | string;
  const SHELL_VERSION: string[];
  const UUID: string;
}

export {};
`;
fs.writeFileSync(path.join(genDir, 'globals.d.ts'), dtsContent, 'utf8');
console.log(`Wrote ${path.join(genDir, 'globals.d.ts')}`);

console.log('Generation complete.');